import os

POSTGRES_USER=os.environ.get('POSTGRES_USER')
POSTGRES_PASSWORD=os.environ.get('POSTGRES_PASSWORD')
POSTGRES_DB = os.environ.get('POSTGRES_DB')
DATABASE_PORT=os.environ.get('DATABASE_PORT')
DATABASE_PORT_HOST_DOCKER=os.environ.get('DATABASE_PORT_HOST_DOCKER')
HOST_DB=os.environ.get('DATABASE_HOST')


SQLALCHEMY_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{HOST_DB}:5432/{POSTGRES_DB}"
SQLALCHEMY_URL_ALEMBIC = f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{HOST_DB}:5432/{POSTGRES_DB}"