"""initial

Revision ID: b3a87a0fe346
Revises: 
Create Date: 2023-09-23 19:07:14.215378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a87a0fe346'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e', sa.String(length=255), nullable=False),
    sa.Column('E', sa.Integer(), nullable=False),
    sa.Column('s', sa.String(length=255), nullable=False),
    sa.Column('U', sa.Integer(), nullable=False),
    sa.Column('u', sa.Integer(), nullable=False),
    sa.Column('b', sa.JSON(), nullable=True),
    sa.Column('a', sa.JSON(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binance_history_last_key_redis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binance_history_last_key_redis')
    op.drop_table('binance')
    # ### end Alembic commands ###
